title: BSG Electronics Blog
description: Technical articles and build notes
theme: minima
permalink: /:title/

# Required for custom domain
url: https://blog.bsgelectronics.com

# MUST be empty or removed for custom domain
# baseurl: /blog
